radio/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^noticias/$', views.noticias_por_categoria, name='noticias'),
     url(r'^lista-noticias/(?P<slug>[\w-]+)/$', views.noticias_locales, name='lista-noticia'),
     url(r'^producciones/(?P<slug>[\w-]+)/$', views.produccion_locales, name='lista-produccion'),
    url(r'^noticias/(?P<subcategoria>[\w-]+)/(?P<slug>[\w-]+)/$', views.DetailNoticias, name='noticia-detalle'),
    url(r'^contacto/$', views.contacto, name='contacto'),
    url(r'^galerias/(?P<slug>[\w-]+)/$', views.GaleriaDetailView.as_view(), name='galeria-detalle'),
    url(r'^producciones/$', views.lista_producciones, name='producciones'),
    url(r'^producciones/(?P<subcategoria>[\w-]+)/(?P<slug>[\w-]+)/$', views.DetailProduccion, name='produccion-detalle'),
]

radio_camoapa/urls.py
# -*- coding: utf-8 -*-
"""radio_camoapa URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from radio.feeds import LatestArticulosFeed
from django.views.generic import TemplateView
from parrila_programacion.views import *

admin.site.site_header = "Administración Radio Camoapa"
admin.site.site_title = "Administración Radio Camoapa"

from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from radio.models import Articulos

from django.contrib.sitemaps import Sitemap

class ArticulosSitemap(Sitemap):
    changefreq = "never"
    priority = 0.5
    protocol = 'https'

    def items(self):
        return Articulos.objects.filter(aprobacion = 2)

    def lastmod(self, obj):
        return obj.fecha

sitemaps = {
    'static': ArticulosSitemap,
}

urlpatterns = [
    url(r'', include('radio.urls')),
    #url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^rss/$', LatestArticulosFeed()),
    url(r'^busqueda/', include('django_google_cse.urls')),
    url(r'^ads\.txt$', TemplateView.as_view(template_name='ads.txt')),
    url(r'^programacion', programacion, name='programacion'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps,'template_name': 'custom_sitemap.html'},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',content_type="text/plain")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

urlpatterns += staticfiles_urlpatterns()

parrila_programacion/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from sorl.thumbnail import ImageField

# Create your models here.
DIA_CHOICES = ((1,'Domingo'),(2,'Lunes'),(3,'Martes'),(4,'Miércoles'),
                (5,'Jueves'),(6,'Viernes'),(7,'Sábado'))

class Programacion(models.Model):
    dia = models.IntegerField(choices=DIA_CHOICES)

    def __str__(self):
        return self.get_dia_display().encode('utf-8')

    class Meta:
        verbose_name_plural = 'Programaciones'

class ProgramacionDia(models.Model):
    programacion = models.ForeignKey(Programacion)
    titulo = models.CharField(max_length=250)
    descripcion = models.TextField()
    hora_inicio = models.TimeField()
    hora_fin = models.TimeField(blank=True, null=True)
    imagen = ImageField(upload_to='programacion/',blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Programacion del dia'

radio/forms.py
# -*- coding: UTF-8 -*-
from django.db import models
from models import *
from django import forms
from django.forms import ModelForm

class EmailForm(forms.Form):
      name = forms.CharField(max_length=255)
      email = forms.EmailField()
      message = forms.CharField(widget=forms.Textarea)

radio/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from radio.models import *
from multimedia.models import *
from datetime import datetime
from itertools import chain
from radio.forms import *
from django.template.loader import render_to_string
from django.core.mail import send_mail, EmailMultiAlternatives
import time
from datetime import datetime
from parrila_programacion.models import *
import locale
from django.db.models import Q, F
from django.db.models.functions import Now
# Create your views here.

class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        #articulos principales
        HOY_ES = datetime.now()
        # noticias_locales = Articulos.objects.filter(categoria_id=1,subcategoria_id=7,aprobacion=2,fecha__lte=HOY_ES).order_by('-fecha').select_related().values_list('imagen_portada','url','imagen_alterna','categoria__nombre','subcategoria__subcategoria','contenido','titulo','fecha')[:1]
        # # Articulos.objects.filter(categoria=1, subcategoria=7,aprobacion=2,fecha__lte=HOY_ES).select_related('categoria').order_by('-fecha')[:1]
        # noticias_nacionales = Articulos.objects.filter(categoria_id=1,subcategoria_id=1,aprobacion=2,fecha__lte=HOY_ES).order_by('-fecha').select_related().values_list('imagen_portada','url','imagen_alterna','categoria__nombre','subcategoria__subcategoria','contenido','titulo','fecha')[:1]
        # # Articulos.objects.filter(categoria=1, subcategoria=1,aprobacion=2,fecha__lte=HOY_ES).select_related('categoria').order_by('-fecha')[:1]
        # noticias_internacionales = Articulos.objects.filter(categoria_id=1,subcategoria_id=2,aprobacion=2,fecha__lte=HOY_ES).order_by('-fecha').select_related().values_list('imagen_portada','url','imagen_alterna','categoria__nombre','subcategoria__subcategoria','contenido','titulo','fecha')[:1]
        # # Articulos.objects.filter(categoria=1, subcategoria=2,aprobacion=2,fecha__lte=HOY_ES).select_related('categoria').order_by('-fecha')[:1]
        # art_principal = list(chain(noticias_locales, noticias_nacionales, noticias_internacionales))

        # ultimas_cat = Articulos.objects.filter(categoria=1,aprobacion=2,fecha__lte=HOY_ES).select_related('categoria').values_list('subcategoria').distinct('subcategoria').order_by('subcategoria')[:6]
        dict = {}
        for value in SubCategorias.objects.filter(categoria=1).select_related('categoria').order_by('subcategoria'):
            articulos = Articulos.objects.filter(categoria=1,subcategoria = value.id,aprobacion=2,fecha__lte=HOY_ES).select_related('categoria').order_by('-fecha')[:2]
            if  articulos:
                dict[value.subcategoria] = articulos

        # context['principal'] = art_principal

        #ultimas noticias
        ultimas_notas = Articulos.objects.filter(fecha__lte=HOY_ES).order_by('-fecha').select_related('categoria','subcategoria')
        context['ultimas_noticias'] = ultimas_notas[:9]
        context['ultimas'] = Articulos.objects.filter(destacado=1,fecha__lte=HOY_ES).distinct('subcategoria').order_by('subcategoria','-fecha').exclude(titulo = ultimas_notas.first())[:4]
        context['patrocinador'] = Patrocinadores.objects.all()
        context['galerias'] = Galerias.objects.filter(fecha__lte=HOY_ES,aprobado=1).order_by('-id')[:6]
        #
        context['notas_subcategorias'] = dict

        #programacion de la hora y el dia
        hoy = datetime.today()
        tupla_diassem = ("lunes", "martes", "miércoles", "jueves","viernes", "sábado","domingo")
        tupla_valores = datetime.isocalendar(hoy)
        dia = 0
        for value in DIA_CHOICES:
            if tupla_diassem[tupla_valores[2]-1].encode('utf-8') in value[1].lower().encode('utf-8'):
                dia = value[0]
        ###########

        context['programacion'] = ProgramacionDia.objects.filter(programacion__dia = dia)
        context['now'] = datetime.now().time()
        return context

def noticias_por_categoria(request, template='radio/articulos_list.html'):
    HOY_ES = datetime.now()
    noticias_locales = Articulos.objects.filter(categoria__slug='noticias', subcategoria__slug='locales',aprobacion=2,fecha__lte=HOY_ES).order_by('-fecha')[:4]
    noticias_nacionales = Articulos.objects.filter(categoria__slug='noticias', subcategoria__slug='nacionales',aprobacion=2,fecha__lte=HOY_ES).order_by('-fecha')[:4]
    noticias_internacionales = Articulos.objects.filter(categoria__slug='noticias', subcategoria__slug='internacionales',aprobacion=2,fecha__lte=HOY_ES).order_by('-fecha')[:4]

    print(noticias_locales)

    return render(request, template, locals())

def noticias_locales(request, slug='None', template='radio/lista_noticias.html'):
    HOY_ES = datetime.now()
    tipo = slug
    noticias = Articulos.objects.filter(categoria__slug='noticias',subcategoria__slug=slug, aprobacion=2,fecha__lte=HOY_ES).order_by('-fecha')
    object_list = noticias

    return render(request, template, locals())

class ListNoticias(ListView):
    model = Articulos
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(ListNoticias, self).get_context_data(**kwargs)
        context['noticias_destacadas'] = Articulos.objects.order_by('-id')[:6]
        return context

def DetailNoticias(request,subcategoria=None,slug=None):
    template = "detalle_noticia.html"
    object = Articulos.objects.get(subcategoria__slug = subcategoria,slug = slug)
    notas_relacionadas = Articulos.objects.filter(subcategoria__slug = subcategoria).exclude(id = object.id).order_by('-fecha')[:6]
    fotos = Fotos.objects.filter(object_id = object.id)

    return render(request, template, locals())

class GaleriaDetailView(DetailView):
    model = Galerias
    template_name = "galeria_detail.html"

    def get_context_data(self, **kwargs):
        HOY_ES = datetime.now()
        context = super(GaleriaDetailView, self).get_context_data(**kwargs)
        context['galerias_relacionadas'] = Galerias.objects.filter(fecha__lte=HOY_ES,tags__in=self.object.tags,aprobado=1).exclude(id=self.object.id).order_by('-fecha')[:6]
        return context

class ContactoView(TemplateView):
    template_name = "contacto.html"

    def get_context_data(self, **kwargs):
        context = super(ContactoView, self).get_context_data(**kwargs)

        #staff
        context['prensa'] = StaffRadio.objects.filter(area = '1')
        context['admon'] = StaffRadio.objects.filter(area = '2')
        context['produccion'] = StaffRadio.objects.filter(area = '3')
        context['locucion'] = StaffRadio.objects.filter(area = '4')

        return context

def contacto(request, template="contacto.html"):
    #staff
    prensa = StaffRadio.objects.filter(area = '1')
    admon = StaffRadio.objects.filter(area = '2')
    produccion = StaffRadio.objects.filter(area = '3')
    locucion = StaffRadio.objects.filter(area = '4')

    arreglo_mail = ['info@radiocamoapa.com',]
    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            try:
                text_content = render_to_string('notify.txt',{'name': name,'email': email,'message':message})
                send_mail('Web Radio Camoapa', text_content, 'noreply@radiocamoapa.com', arreglo_mail)

                enviado = 1

            except:
                pass
        else:
			enviado = 0

    else:
        form = EmailForm()

    return render(request, template, locals())

def lista_producciones(request, template='radio/producciones.html'):
    HOY_ES = datetime.now()
    todo_prod = Articulos.objects.filter(categoria__slug='producciones', aprobacion=2,fecha__lte=HOY_ES).order_by('-fecha')
    object_list = todo_prod

    return render(request, template, locals())

def produccion_locales(request, slug='None', template='radio/producciones.html'):
    tipo = slug
    HOY_ES = datetime.now()
    noticias = Articulos.objects.filter(categoria__slug='producciones',subcategoria__slug=slug, aprobacion=2,fecha__lte=HOY_ES).order_by('-fecha')
    object_list = noticias

    return render(request, template, locals())

def DetailProduccion(request,subcategoria=None,slug=None):
    template = "detalle_produccion.html"
    #object = Articulos.objects.filter(categoria__slug='producciones', aprobacion=2,fecha__lte=HOY_ES).order_by('-fecha')
    object = Articulos.objects.get(subcategoria__slug = subcategoria,slug = slug)
    notas_relacionadas = Articulos.objects.filter(subcategoria__slug = subcategoria).exclude(id = object.id).order_by('-fecha')[:6]
    fotos = Fotos.objects.filter(object_id = object.id)

    return render(request, template, locals())

templates/radio/articulos_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% load embed_video_tags %}

{% block extra_css %}

{% endblock %}


{% block content %}
<div class="article-list pb-70">
    <div class="container-box">
        <div class="row">
            <div class="col-xl-9 col-lg-9 mb-30">
                <div class="locales-list">
                    <div class="row mb-40">
                        <div class="col-xl-12">
                            <div class="section-title">
                                <div class="row">
                                    <div class="col-md-7">
                                        <h2>Locales</h2>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="more-link more2-link text-md-right">
                                            <a href="/lista-noticias/locales/">Ver más <i class="far fa-long-arrow-right"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        {% for noticia in noticias_locales %}
                        <div class="col-xl-6 col-lg-6 col-md-6 mb-60">
                            <div class="postbox mb-30">
                                <div class="postbox-thumb">
                                    {% if noticia.imagen_portada %}
                                    {% thumbnail noticia.imagen_portada "670x490" crop="center" as img %}
                                    <a href="{% url 'noticia-detalle' noticia.subcategoria.slug noticia.slug%}"><img src="/media/{{img}}" alt="{{noticia.titulo}}" width="100%"></a>
                                    {% endthumbnail %}
                                    {% elif noticia.url %}
                                    {% video noticia.url as video %}
                                    {% thumbnail video.thumbnail "670x490" crop="center" as img %}
                                    <a href="{% url 'noticia-detalle' noticia.subcategoria.slug noticia.slug%}"><img src="/media/{{img}}" alt="{{noticia.titulo}}" width="100%"></a>
                                    {% endthumbnail %}
                                    {% endvideo %}
                                    {% elif noticia.imagen_alterna %}
                                    {% thumbnail noticia.imagen_alterna "670x490" crop="center" as img %}
                                    <a href="{% url 'noticia-detalle' noticia.subcategoria.slug noticia.slug%}"><img src="/media/{{img}}" alt="{{noticia.titulo}}" width="100%"></a>
                                    {% endthumbnail %}
                                    {% else %}
                                    <a href="{% url 'noticia-detalle' noticia.subcategoria.slug noticia.slug%}"><img src="https://via.placeholder.com/670x490" alt="{{noticia.titulo}}" width="100%"></a>
                                    {% endif %}
                                </div>
                                <div class="post-fea-cat">
                                    <a href="#">{{noticia.categoria}} </a>
                                </div>
                                <div class="postbox-text post-text-last">
                                    <div class="post-wr-cat">
                                        <a href="#">{{noticia.subcategoria}}</a>
                                    </div>
                                    <div class="post-wr-meta mt-15"><span class="base_color"><a href="#">{{noticia.fecha|date:"l d F Y"}}</a></span></div>
                                    <h5 class="f-18 mt-0"><a class="text-limit-3" href="{% url 'noticia-detalle' noticia.subcategoria.slug noticia.slug%}">{{noticia.titulo}}</a></h5>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>

                <div class="nacionales-list">
                    <div class="row mb-40">
                        <div class="col-xl-12">
                            <div class="section-title">
                                <div class="row">
                                    <div class="col-md-7">
                                        <h2>Nacionales</h2>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="more-link more2-link text-md-right">
                                            <a href="/lista-noticias/nacionales/">Ver más <i class="far fa-long-arrow-right"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        {% for noticia in noticias_nacionales %}
                        <div class="col-xl-6 col-lg-6 col-md-6 mb-60">
                            <div class="postbox mb-30">
                                <div class="postbox-thumb">
                                    {% if noticia.imagen_portada %}
                                    {% thumbnail noticia.imagen_portada "670x490" crop="center" as img %}
                                    <a href="{% url 'noticia-detalle' noticia.subcategoria.slug noticia.slug%}"><img src="/media/{{img}}" alt="{{noticia.titulo}}" width="100%"></a>
                                    {% endthumbnail %}
                                    {% elif noticia.url %}
                                    {% video noticia.url as video %}
                                    {% thumbnail video.thumbnail "670x490" crop="center" as img %}
                                    <a href="{% url 'noticia-detalle' noticia.subcategoria.slug noticia.slug%}"><img src="/media/{{img}}" alt="{{noticia.titulo}}" width="100%"></a>
                                    {% endthumbnail %}
                                    {% endvideo %}
                                    {% elif noticia.imagen_alterna %}
                                    {% thumbnail noticia.imagen_alterna "670x490" crop="center" as img %}
                                    <a href="{% url 'noticia-detalle' noticia.subcategoria.slug noticia.slug%}"><img src="/media/{{img}}" alt="{{noticia.titulo}}" width="100%"></a>
                                    {% endthumbnail %}
                                    {% else %}
                                    <a href="{% url 'noticia-detalle' noticia.subcategoria.slug noticia.slug%}"><img src="https://via.placeholder.com/670x490" alt="{{noticia.titulo}}" width="100%"></a>
                                    {% endif %}
                                </div>
                                <div class="post-fea-cat">
                                    <a href="#">{{noticia.categoria}} </a>
                                </div>
                                <div class="postbox-text post-text-last">
                                    <div class="post-wr-cat">
                                        <a href="#">{{noticia.subcategoria}}</a>
                                    </div>
                                    <div class="post-wr-meta mt-15"><span class="base_color"><a href="#">{{noticia.fecha|date:"l d F Y"}}</a></span></div>
                                    <h5 class="f-18 mt-0"><a class="text-limit-3" href="{% url 'noticia-detalle' noticia.subcategoria.slug noticia.slug%}">{{noticia.titulo}}</a></h5>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>

                <div class="internacionales-list">
                    <div class="row mb-40">
                        <div class="col-xl-12">
                            <div class="section-title">
                                <div class="row">
                                    <div class="col-md-7">
                                        <h2>Internacionales</h2>
                                    </div>
                                    <div class="col-md-5">
                                        <div class="more-link more2-link text-md-right">
                                            <a href="/lista-noticias/internacionales/">Ver más <i class="far fa-long-arrow-right"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        {% for noticia in noticias_internacionales %}
                        <div class="col-xl-6 col-lg-6 col-md-6 mb-60">
                            <div class="postbox mb-30">
                                <div class="postbox-thumb">
                                    {% if noticia.imagen_portada %}
                                    {% thumbnail noticia.imagen_portada "670x490" crop="center" as img %}
                                    <a href="{% url 'noticia-detalle' noticia.subcategoria.slug noticia.slug%}"><img src="/media/{{img}}" alt="{{noticia.titulo}}" width="100%"></a>
                                    {% endthumbnail %}
                                    {% elif noticia.url %}
                                    {% video noticia.url as video %}
                                    {% thumbnail video.thumbnail "670x490" crop="center" as img %}
                                    <a href="{% url 'noticia-detalle' noticia.subcategoria.slug noticia.slug%}"><img src="/media/{{img}}" alt="{{noticia.titulo}}" width="100%"></a>
                                    {% endthumbnail %}
                                    {% endvideo %}
                                    {% elif noticia.imagen_alterna %}
                                    {% thumbnail noticia.imagen_alterna "670x490" crop="center" as img %}
                                    <a href="{% url 'noticia-detalle' noticia.subcategoria.slug noticia.slug%}"><img src="/media/{{img}}" alt="{{noticia.titulo}}" width="100%"></a>
                                    {% endthumbnail %}
                                    {% else %}
                                    <a href="{% url 'noticia-detalle' noticia.subcategoria.slug noticia.slug%}"><img src="https://via.placeholder.com/670x490" alt="{{noticia.titulo}}" width="100%"></a>
                                    {% endif %}
                                </div>
                                <div class="post-fea-cat">
                                    <a href="#">{{noticia.categoria}} </a>
                                </div>
                                <div class="postbox-text post-text-last">
                                    <div class="post-wr-cat">
                                        <a href="#">{{noticia.subcategoria}}</a>
                                    </div>
                                    <div class="post-wr-meta mt-15"><span class="base_color"><a href="#">{{noticia.fecha|date:"l d F Y"}}</a></span></div>
                                    <h5 class="f-18 mt-0"><a class="text-limit-3" href="{% url 'noticia-detalle' noticia.subcategoria.slug noticia.slug%}">{{noticia.titulo}}</a></h5>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-3 mb-30">
                {% include "sidebar.html" %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/radio/programacion.html
{% extends "base.html" %}
{% block extra_css %}
{% endblock %}

{% block content %}
<div class="producciones pb-70">
    <div class="container-box">
        <div class="row mb-40">
            <div class="col-xl-12">
                <div class="section-title">
                    <div class="row">
                        <div class="col-md-12">
                            <h2>Parrilla de programación</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-12">
                <!-- Nav tabs -->
                <ul class="nav nav-pills mb-3 nav-justified" id="myTab" role="tablist">
                    {% for obj in object_list %}
                    <li class="nav-item" role="presentation">
                        <a class="nav-link {% if day|date:"l" == obj.get_dia_display %}active{% endif %}
                        " id="{{obj}}-tab" data-bs-toggle="tab" href="#{{obj}}" role="tab" aria-controls="{{obj}}" aria-selected="true">{{obj}}</a>
                    </li>
                    {% endfor %}

                </ul>

                <!-- Tab panes -->
                <div class="tab-content list-programacion">
                  {% for obj in object_list  %}
                  <div class="tab-pane {% if day|date:"l" == obj.get_dia_display %}active{% endif %}" id="{{obj}}" role="tabpanel" aria-labelledby="{{obj}}-tab">
                      <ul class="list-group lis">
                      {% for item in obj.programaciondia_set.all|dictsort:"hora_inicio" %}
                      <li class="list-group-item {% if now >= item.hora_inicio and now <= item.hora_fin and day|date:"l" == obj.get_dia_display %}active{% endif %}">
                          <div class="p-encabezado">
                              <div class="p-hora">
                                  {{item.hora_inicio|time:"h:i a"}}{% if item.hora_fin %} - {{item.hora_fin|time:"h:i a"}}{% endif %}
                              </div>
                              <div class="p-titulo">
                                  {{item.titulo}}
                              </div>
                          </div>
                          <div class="p-descripcion">
                              {{item.descripcion}}
                          </div>
                      </li>
                      {% endfor %}
                      </ul>
                  </div>

                  {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block extra_js %}
<script>
    $('.nav-pills a').click(function(){
        $(this).tab('show');
        $('html, body').animate({
            scrollTop: $('.producciones .nav-justified').offset().top-20
        }, 800);
      });

</script>

{% endblock extra_js %}