radio/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^noticias/$', views.noticias_por_categoria, name='noticias'),
     url(r'^lista-noticias/(?P<slug>[\w-]+)/$', views.noticias_locales, name='lista-noticia'),
     url(r'^producciones/(?P<slug>[\w-]+)/$', views.produccion_locales, name='lista-produccion'),
    url(r'^noticias/(?P<subcategoria>[\w-]+)/(?P<slug>[\w-]+)/$', views.DetailNoticias, name='noticia-detalle'),
    url(r'^contacto/$', views.contacto, name='contacto'),
    url(r'^galerias/(?P<slug>[\w-]+)/$', views.GaleriaDetailView.as_view(), name='galeria-detalle'),
    url(r'^producciones/$', views.lista_producciones, name='producciones'),
    url(r'^producciones/(?P<subcategoria>[\w-]+)/(?P<slug>[\w-]+)/$', views.DetailProduccion, name='produccion-detalle'),
]

radio_camoapa/urls.py
# -*- coding: utf-8 -*-
"""radio_camoapa URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from radio.feeds import LatestArticulosFeed
from django.views.generic import TemplateView
from parrila_programacion.views import *

admin.site.site_header = "Administración Radio Camoapa"
admin.site.site_title = "Administración Radio Camoapa"

from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from radio.models import Articulos

from django.contrib.sitemaps import Sitemap

class ArticulosSitemap(Sitemap):
    changefreq = "never"
    priority = 0.5
    protocol = 'https'

    def items(self):
        return Articulos.objects.filter(aprobacion = 2)

    def lastmod(self, obj):
        return obj.fecha

sitemaps = {
    'static': ArticulosSitemap,
}

urlpatterns = [
    url(r'', include('radio.urls')),
    #url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^rss/$', LatestArticulosFeed()),
    url(r'^busqueda/', include('django_google_cse.urls')),
    url(r'^ads\.txt$', TemplateView.as_view(template_name='ads.txt')),
    url(r'^programacion', programacion, name='programacion'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps,'template_name': 'custom_sitemap.html'},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt',content_type="text/plain")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

urlpatterns += staticfiles_urlpatterns()

radio/forms.py
# -*- coding: UTF-8 -*-
from django.db import models
from models import *
from django import forms
from django.forms import ModelForm

class EmailForm(forms.Form):
      name = forms.CharField(max_length=255)
      email = forms.EmailField()
      message = forms.CharField(widget=forms.Textarea)

templates/contacto.html
{% extends "base.html" %}
{% load thumbnail %}

{% block extra_css %}

{% endblock %}

{% block content %}
<div class="contact-area pb-75">
    <div class="container-box">
        <div class="row mb-40">
            <div class="col-xl-12">
                <div class="section-title">
                    <div class="row">
                        <div class="col-md-12">
                            <h2>Staff de la radio</h2>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
        <div class="row">
            {% if prensa %}
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12">
                        <h4 class="mb-0">Prensa</h4>
                        <hr class="mb-10 mt-10">
                    </div>
                </div>
                <div id="" class="row">
                    {% for obj in prensa %}
                    <div class="col-lg-6 col-md-6 col-md-6 grid-item cat2 cat4 cat1">
                        <div class="portfolio-wrapper mb-60">
                            <div class="portfolio-caption">
                                <h5><a>{{obj.nombre}}</a></h5>
                                <span>{{obj.cargo}}</span>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}

            {% if admon %}
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12">
                        <h4 class="mb-0">Administración</h4>
                        <hr class="mb-10 mt-10">
                    </div>
                </div>
                <div id="" class="row">
                    {% for obj in admon %}
                    <div class="col-lg-6 col-md-6 col-md-6 grid-item cat2 cat4 cat1">
                        <div class="portfolio-wrapper mb-60">
                            <div class="portfolio-caption">
                                <h5><a>{{obj.nombre}}</a></h5>
                                <span>{{obj.cargo}}</span>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    
                </div>
            </div>
            {% endif %}

            {% if produccion %}
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12">
                        <h4 class="mb-0">Producción</h4>
                        <hr class="mb-10 mt-10">
                    </div>
                </div>
                <div id="" class="row">
                    {% for obj in produccion %}
                    <div class="col-lg-6 col-md-6 col-md-6 grid-item cat2 cat4 cat1">
                        <div class="portfolio-wrapper mb-60">
                            <div class="portfolio-caption">
                                <h5><a>{{obj.nombre}}</a></h5>
                                <span>{{obj.cargo}}</span>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}

            {% if locucion %}
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12">
                        <h4 class="mb-0">Locucion</h4>
                        <hr class="mb-10 mt-10">
                    </div>
                </div>
                <div id="" class="row">
                    {% for obj in locucion %}
                    <div class="col-lg-6 col-md-6 col-md-6 grid-item cat2 cat4 cat1">
                        <div class="portfolio-wrapper mb-60">
                            <div class="portfolio-caption">
                                <h5><a>{{obj.nombre}}</a></h5>
                                <span>{{obj.cargo}}</span>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
<!-- contact-area-satrt -->
<div class="contact-area pb-75">
    <div class="container-box">
        
        <div class="row mb-40">
            <div class="col-xl-12">
                <div class="section-title">
                    <div class="row">
                        <div class="col-md-12">
                            <h2>Escríbenos</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-3 col-lg-3 mb-30">
                <div class="contact-adddress-wrapper">
                    <ul class="contact-list-address">
                        <li>
                            <div class="contact-address-text">
                                <h3>Dirección</h3>
                                <p>Del Mercado Municipal 2 cuadras al Este, Camoapa, Nicaragua</p>
                            </div>
                        </li>
                        <li>
                            <div class="contact-address-text">
                                <h3>Correo</h3>
                                <p><a href="mailto:direccion@radiocamoapa.com">direccion@radiocamoapa.com</a></p>
                            </div>
                        </li>
                        <li>
                            <div class="contact-address-text">
                                <h3>Teléfonos</h3>
                                <p> (+505) 2549 2327 / (+505) 2549-2474 / (+505) 8420-9070</p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-xl-9 col-lg-9 mb-30">
                <div class="row">
                    <div class="col-xl-12">
                        <form id="contact-form" action="." method="POST">{% csrf_token %}
                            <div class="row">
                                <div class="col-xl-4 col-md-4">
                                    {{form.name}}
                                </div>
                                <div class="col-xl-8 col-md-8">
                                    {{form.email}}
                                </div>
                                <div class="col-xl-12">
                                    {{form.message}}
                                    <!-- <textarea name="message" cols="30" rows="10" placeholder="Write here: "></textarea> -->
                                    
                                    <input class="btn " type="submit" value="Enviar">
                                </div>
                            </div>
                            <p class="ajax-response"></p>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-12">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4634.321396707377!2d-85.51251541777128!3d12.383986515304695!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8f73735b550953a1%3A0x1463bedacfb9840c!2sRadio+Camoapa+Est%C3%A9reo!5e0!3m2!1ses-419!2sni!4v1475529312290" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen=""></iframe>
            </div>
        </div>
    </div>
</div>
<!-- contact-area-satrt -->
{% endblock %}
{% block extra_js %}
<script>
    $("#id_name").attr("placeholder", "Nombre:");
    $("#id_email").attr("placeholder", "Correo:");
    $("#id_message").attr("placeholder", "Escriba aquí");
</script>

{% endblock extra_js %}

templates/custom_sitemap.html
<?xml version="1.0" encoding="UTF-8"?>
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:news="http://www.google.com/schemas/sitemap-news/0.9">
{% spaceless %}
{% for url in urlset %}
  <url>
    <loc>{{ url.location }}</loc>
    {% if url.lastmod %}<lastmod>{{ url.lastmod|date:"Y-m-d" }}</lastmod>{% endif %}
    {% if url.changefreq %}<changefreq>{{ url.changefreq }}</changefreq>{% endif %}
    {% if url.priority %}<priority>{{ url.priority }}</priority>{% endif %}
    <news:news>
      {% if url.item.fecha %}<news:publication_date>{{ url.item.fecha|date:"Y-m-d" }}</news:publication_date>{% endif %}
      {% if url.item.tags %}<news:keywords>{{ url.item.tags }}</news:keywords>{% endif %}
    </news:news>
   </url>
{% endfor %}
{% endspaceless %}
</urlset>

templates/detalle_produccion.html
{% extends "base.html" %}

{% load disqus_tags %}
{% disqus_dev %}
{% load thumbnail %}
{% load tagging_tags %}
{% load embed_video_tags %}
{% load helpertags %}

{% block extra_css %}
{% endblock %}

{% block share_fb %}
<meta property="og:title" content="{{object.titulo}}" />
<meta property="og:type" content="article" />
{% if object.imagen_portada %}
	<meta property="og:image" content="https://radiocamoapa.com/media/{{object.imagen_portada}}">
{% elif object.url %}
 	{% video object.url as video %}
		<meta property="og:image" content="{{video.thumbnail}}">
	{% endvideo %}
{% endif %}

<meta property="og:image:width" content="300" />
<meta property="og:image:height" content="300" />
<meta property="og:description" content="{{object.contenido|striptags}}" />
<meta property="og:url" content="https://radiocamoapa.com{{request.path}}" />
<meta property="og:locale" content="es_ES" />

<!-- twitter -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{{object.titulo}}">
<meta name="twitter:description" content="{{object.contenido|striptags}}">
{% if object.imagen_portada %}
	<meta name="twitter:image" content="https://radiocamoapa.com/media/{{object.imagen_portada}}">
{% elif object.url %}
 	{% video object.url as video %}
		<meta property="twitter:image" content="{{video.thumbnail}}">
	{% endvideo %}
{% endif %}
<meta name="twitter:domain" content="https://radiocamoapa.com">
{% endblock share_fb %}


{% block content %}
    <div class="enterteinment-area pb-70">
        <div class="container-box">
            <div class="row">
                <div class="col-xl-9 col-lg-9 mb-30">
                    <div class="blog-details-wrapper">
                        <div class="post-padding  post2-padding post-3-padding blog-details-paddiing">
                            <div class="inner-post-wrapper">
                                <div class="post-wrapper">
                                    <div class="post-wr-meta mt-0">
                                        <span><a>{{object.fecha|date:"l d F Y"}} Hora:{{ object.fecha|time:"P" }}</a></span><br>
                                        <span><a>Por {{object.user.get_full_name}}</a></span>
                                    </div>
                                    <h3 class="pos-wr-title"><a href="">{{object.titulo}}</a></h3>
                                    <div class="post-wr-img mb-50">
                                        {% if object.imagen_portada %}
                                        {% thumbnail object.imagen_portada "670x490" crop="center" as img %}
                                        <img src="/media/{{img}}" alt="{{object.titulo}}" width="100%">
                                        {% endthumbnail %}
                                        {% elif object.url %}
                                        {% video object.url as video %}
                                        {% thumbnail video.thumbnail "670x490" crop="center" as img %}
                                        <img src="/media/{{img}}" alt="{{object.titulo}}" width="100%">
                                        {% endthumbnail %}
                                        {% endvideo %}
                                        {% elif object.imagen_alterna %}
                                        {% thumbnail object.imagen_alterna "670x490" crop="center" as img %}
                                        <img src="/media/{{img}}" alt="{{object.titulo}}" width="100%">
                                        {% endthumbnail %}
                                        {% else %}
                                        <img src="https://via.placeholder.com/670x490" alt="{{object.titulo}}" width="100%">
                                        {% endif %}
                                        {% if object.credito_foto_portada %}
                                        <p class="pt-10 pb-10 text-center foto-detalle">
                                            {{object.credito_foto_portada}}
                                        </p>
                                        {% endif %}
                                    </div>
                                    <div class="post-content">
                                        {{object.contenido|safe}}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="user-info">
                            <div class="user-text">
                                {% tags_for_object object as tag_cloud %}
                                {% for obj in  tag_cloud %}
                                <a href="#">{{obj}}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 mb-30">
                    {% include "sidebar.html" %}
                </div>
                <div class="col-lg-12">
                    {% disqus_show_comments %}
                </div>
            </div>
            <div class="row">
                <div class="tready-news-area pb-60">
                    <div class="container">
                        <div class="pt-60 pb-25">
                            <div class="row">
                                <div class="col-xl-12 col-lg-12 col-md-12">
                                    <div class="row mb-40">
                                        <div class="col-xl-12">
                                            <div class="section-title">
                                                <div class="row">
                                                    <div class="col-md-7">
                                                        <h2>Noticias relacionadas</h2>
                                                    </div>
                                                    
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="news-relacionada owl-carousel">
                                            {% for obj in notas_relacionadas %}
                                            <div class="col">
                                                <div class="postbox mb-30">
                                                    <div class="postbox-thumb">
                                                        {% if obj.imagen_portada %}
                                                        {% thumbnail obj.imagen_portada "670x490" crop="center" as img %}
                                                        <a href="{% url 'noticia-detalle' obj.subcategoria.slug obj.slug %}"><img src="/media/{{img}}" alt="{{obj.titulo}}" width="100%"></a>
                                                        {% endthumbnail %}
                                                        {% elif obj.url %}
                                                        {% video obj.url as video %}
                                                        {% thumbnail video.thumbnail "670x490" crop="center" as img %}
                                                        <a href="{% url 'noticia-detalle' obj.subcategoria.slug obj.slug %}"><img src="/media/{{img}}" alt="{{obj.titulo}}" width="100%"></a>
                                                        {% endthumbnail %}
                                                        {% endvideo %}
                                                        {% elif obj.imagen_alterna %}
                                                        {% thumbnail obj.imagen_alterna "670x490" crop="center" as img %}
                                                        <a href="{% url 'noticia-detalle' obj.subcategoria.slug obj.slug %}"><img src="/media/{{img}}" alt="{{obj.titulo}}" width="100%"></a>
                                                        {% endthumbnail %}
                                                        {% else %}
                                                        <img src="via.placeholder.com/670x490" alt="{{obj.titulo}}">
                                                        <a href="{% url 'noticia-detalle' obj.subcategoria.slug obj.slug %}"><img src="https://via.placeholder.com/670x490" alt="{{obj.titulo}}" width="100%"></a>
                                                        {% endif %}
                                                    </div>
                                                    <div class="post-fea-cat">
                                                        <a href="#">{{obj.categoria}} </a>
                                                    </div>
                                                    <div class="postbox-text post-text-last">
                                                        <div class="post-wr-cat">
                                                            <a href="#">{{obj.subcategoria}}</a>
                                                        </div>
                                                        <h5 class="f-18"><a class="text-limit-3" href="{% url 'noticia-detalle' obj.subcategoria.slug obj.slug %}">{{obj.titulo}}</a></h5>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            {% endfor %}
                                        </div>
                                        
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="si-sticky slideleft">
        <ul class="social-share">
            <li class="main_icon">
                <i class="fas fa-share-square"></i>
            </li>
            <li>
                <a href="https://twitter.com/share?url=https://radiocamoapa.com{{request.path}}&amp;text={{object.titulo}}" target="_blank" class="tw">
                    <i class="fab fa-twitter"></i>
                </a>
            </li>
            <li>
                <a href="https://www.facebook.com/sharer.php?u=https://radiocamoapa.com{{request.path}}" target="_blank" class="fb">
                    <i class="fab fa-facebook-f"></i>
                </a>
            </li>
            <li>
                <a href="https://wa.me/?text=https://radiocamoapa.com{{request.path}}" target="_blank" class="wt" >
                    <i class="fab fa-whatsapp"></i>
                </a>
            </li>
            <li>
                <a href="mailto:?subject={{obj.titulo}}&amp;body=Visitanos en https://radiocamoapa.com{{request.path}}"  class="gp">
                    <i class="fas fa-envelope"></i>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}
{% block extra_js %}
<script>
    $(".post-content blockquote").addClass("blockquote");
    $(".post-content ul").addClass("blog-details-link");
    $(".post-content ul li").prepend( "<i class='far fa-check'></i>" ); 
</script>
<script>
    var tamano = $('.tready-news-area').offset().top;
    var tamano2 = $('.enterteinment-area').offset().top;
    //alert(tamano);
    $(document).scroll(function() {
        if($('.si-sticky').offset().top >= tamano || $('.si-sticky').offset().top <= tamano2 ){
            $('.si-sticky').addClass('slideleft');
        }else{

            $('.si-sticky').removeClass('slideleft');
        }
    });

    
   
    
</script>
{% endblock extra_js %}

templates/galeria_detail.html
{% extends "base.html" %}

{% load thumbnail %}
{% load tagging_tags %}

{% block share_fb %}
<meta property="og:title" content="{{object.titulo}}" />
<meta property="og:type" content="article" />
{% for obj in object.galeria.all|slice:":1" %}
  <meta property="og:image" content="https://radiocamoapa.com/media/{{obj}}">
{% endfor %}
<meta property="og:image:width" content="300" />
<meta property="og:image:height" content="300" />
<meta property="og:description" content="{{object.resumen|striptags}}" />
<meta property="og:url" content="https://radiocamoapa.com{{request.path}}" />
<meta property="og:locale" content="es_ES" />
{% endblock share_fb %}

{% block content %}
<div class="galeria-detalle pb-70">
    <div class="container-box">
        <div class="row">
            <div class="col-xl-9 col-lg-9 mb-30">
                <div class="blog-details-wrapper">
                    <div class="post-padding  post2-padding post-3-padding blog-details-paddiing">
                        <div class="inner-post-wrapper">
                            <div class="post-wrapper">
                                <div class="post-wr-meta mt-0">
                                    <span><a>{{object.fecha|date:"l d F Y"}}</a></span><br>
                                </div>
                                <h3 class="pos-wr-title"><a href="">{{object.titulo}}</a></h3>
                                <div class="post-wr-img mb-50">
                                    {% if object.portada %}
                                        {% thumbnail object.portada "670x490" crop="center" as img %}
                                            <img src="/media/{{img}}" alt="{{object.titulo}}" width="100%">
                                        {% endthumbnail %}
                                    {% else %}
                                        <img src="https://via.placeholder.com/670x490" alt="{{noticia.titulo}}" width="100%">
                                    {% endif %}
                                </div>
                                <div class="post-content mb-30">
                                    {{object.resumen|safe}}
                                </div>
                                <div id="portfolio-grid" class="row row-portfolio">
                                    <div class="grid-sizer"></div>
                                    {% for obj in object.galeria.all %}
                                    <div class="col-lg-4 col-md-4 col-md-6 grid-item cat2 cat4 cat1 mb-30">
                                        {% if obj.foto %}
                                        <a class="portfolio-wrapper popup-image" href="/media/{{obj.foto}}">
                                            <div class="portfolio-image">                                                
                                                {% thumbnail obj.foto "670x490" crop="center" as img %}
                                                <img src="/media/{{img}}" width="100%" alt="{{obj.titulo}}">
                                                {% endthumbnail %}                                                
                                            </div>
                                            <div class="portfolio-caption">
                                                <h5>{{obj.titulo}}</h5>
                                            </div>
                                        </a>
                                        {% elif obj.foto_url %}
                                        <a class="portfolio-wrapper popup-image" href="{{obj.foto_url}}">
                                            <div class="portfolio-image">
                                                {% thumbnail obj.foto_url "670x490" crop="center" as img %}
                                                <img src="/media/{{img}}" width="100%" alt="{{obj.titulo}}">
                                                {% endthumbnail %}
                                            </div>
                                            <div class="portfolio-caption">
                                                <h5>{{obj.titulo}}</h5>
                                            </div>
                                        </a>
                                        {% endif %}
                                    </div>
                                    {% endfor %}
                                </div>
                               
                            </div>
                        </div>
                    </div>
                    <div class="user-info">
                        <div class="user-text">
                            {% tags_for_object object as tag_cloud %}
                            {% for obj in  tag_cloud %}
                            <a href="#">{{obj}}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-lg-3 mb-30">
                {% include "sidebar.html" %}
            </div>
        </div>
    </div>
</div>
<div class="si-sticky slideleft">
    <ul class="social-share">
        <li class="main_icon">
            <i class="fas fa-share-square"></i>
        </li>
        <li>
            <a href="https://twitter.com/share?url=https://radiocamoapa.com{{request.path}}&amp;text={{object.titulo}}" target="_blank" class="tw">
                <i class="fab fa-twitter"></i>
            </a>
        </li>
        <li>
            <a href="https://www.facebook.com/sharer.php?u=https://radiocamoapa.com{{request.path}}" target="_blank" class="fb">
                <i class="fab fa-facebook-f"></i>
            </a>
        </li>
        <li>
            <a href="https://wa.me/?text=https://radiocamoapa.com{{request.path}}" target="_blank" class="wt" >
                <i class="fab fa-whatsapp"></i>
            </a>
        </li>
        <li>
            <a href="mailto:?subject={{obj.titulo}}&amp;body=Visitanos en https://radiocamoapa.com{{request.path}}"  class="gp">
                <i class="fas fa-envelope"></i>
            </a>
        </li>
    </ul>
</div>
{% endblock %}
{% block extra_js %}
<script>
    $(".post-content blockquote").addClass("blockquote");
    $(".post-content ul").addClass("blog-details-link");
    $(".post-content ul li").prepend( "<i class='far fa-check'></i>" ); 
</script>
<script>
    var tamano2 = $('.galeria-detalle').offset().top;
    //alert(tamano);
    $(document).scroll(function() {
        if( $('.si-sticky').offset().top <= tamano2 ){
            $('.si-sticky').addClass('slideleft');
        }else{

            $('.si-sticky').removeClass('slideleft');
        }
    });

    
   
    
</script>
{% endblock extra_js %}